module.exports = {
    trailingComma: 'es5',
    tabWidth: 4,
    useTabs: false,
    semi: true,
    singleQuote: true,
    printWidth: 120,
    arrowParens: 'avoid',
    bracketSpacing: true,
    htmlWhitespaceSensitivity: 'css',
    quoteProps: 'as-needed',
    vueIndentScriptAndStyle: false,
    jsxSingleQuote: false,
    bracketSameLine: false,
    requirePragma: false,
    insertPragma: false,
    proseWrap: 'preserve',
    endOfLine: 'lf',
};
